domain: "https://baker531.github.io" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://baker531.github.io" # the subpath of your site, e.g. /blog
title: "Baker's Site" # the name of your site, e.g. ACME Corp.
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
exclude:
  - .post-template